development:
  access_key_id: AKIAIYJGCIF577O5EEKQ
  secret_access_key: I8X1hJbRuO/3sh0WLoeFyQEnJVsztTKUbtIXB8p

production:
  access_key_id: AKIAIYJGCIF577O5EEKQ
  secret_access_key: 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
